version: '3'
services:
  capstone:
    image: nginx:latest
    ports:
      - '80:80'
~                                                                                                                                                                                                                  
~                   
